[package]
name = "github-status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.25", features = ["color", "suggestions", "derive"] }
colored = "2.0.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.147", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.88"
