[package]
name = "github-status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.21", features = ["color", "suggestions", "derive"] }
colored = "2.0.0"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.144", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.85"
